### ISSUE TITLE
Are UP GT-s correct when training with large distortion?

### ISSUE THREAD

**Issue by suvigy** [cvg/GeoCalib#24]
Hi!

 I'm trying to train with simple Division camera model, which can also model wide angle fisheye camera models. I created the training data set with the following params, I just hightlight the relevant parts.

```
....
camera_model: simple_divisional
parameter_dists:
  vfov:
     ...
       loc: 1.88
       scale: 0.01 
    ....
  k1:
    .....
      loc:  -0.29104758148391235
      scale: 0.002
.....
 shape:
    type: fix
    value:
      - 640
      - 960

```

In wandb I'm getting the following visualization also including the up gt, pred, confidence:

![Image](https://github.com/user-attachments/assets/09b4e8bc-f1f9-4ceb-a240-45552a0fcade)

Do you think the 'Up Gt' is correct? To me, it seems that there is mostly an inner circle within which the up vectors are correct, but outside of this circle, they appear to be incorrect. Or should it be interpreted in a different way?
(As shown in the example, out-of-FoV pixels are not yet masked. The simple_division model sets every pixel as valid during undistortion. I hope the UpGt issue isn't related to this; I plan to address the valid pixels later.)
